# Generated by Django 3.2.5 on 2021-07-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210727_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='senders',
            new_name='sender',
        ),
    ]
